# version: 0.0.1
FROM osrf/ros:melodic-desktop-full

# Update package list and install necessary packages
RUN apt-get update && \
    apt-get install -y curl gnupg2 lsb-release libusb-dev && \
    cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
    sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list && \
    sed -i "s/cn.archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list && \
    apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 && \
    sh -c '. /etc/lsb-release && echo "deb http://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu/ `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list' && \
    apt-get update

# Install ROS Dashing desktop and python3-argcomplete
# Install locales and set en_US.UTF-8 locale
RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

# Set environment variables
ENV LANG en_US.UTF-8

RUN curl http://repo.ros2.org/repos.key | sudo apt-key add - && \
	sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list' && \
	apt update

RUN apt-get install -y ros-dashing-desktop python3-argcomplete ros-dashing-rmw-opensplice-cpp ros-dashing-rmw-connext-cpp python3-colcon-common-extensions ros-dashing-launch-testing-ament-cmake

RUN echo 'echo "ros: melodic(1) dashing(2)?"' >> ~/.bashrc && \
    echo 'read choose' >> ~/.bashrc && \
    echo 'case $choose in' >> ~/.bashrc && \
    echo '1) source /opt/ros/melodic/setup.bash ;;' >> ~/.bashrc && \
    echo '2) source /opt/ros/dashing/setup.bash ;;' >> ~/.bashrc && \
    echo 'esac' >> ~/.bashrc

# Clean up apt cache to reduce image size
RUN rm -rf /var/lib/apt/lists/*

# Set the default command to run when starting the container
CMD ["/bin/bash"]

