FROM ubuntu:16.04

# Install sudo and other necessary packages
RUN apt-get update \
    && apt-get install -y sudo \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get install x11-xserver-utils

# Add a user 'lee' with UID/GID 1000 and set password 'lee'
RUN groupadd -g 1000 lee \
    && useradd -u 1000 -g 1000 -m -s /bin/bash lee \
    && echo 'lee:lee' | chpasswd

# Add 'lee' to sudo group and allow sudo with password
RUN usermod -aG sudo lee \
    && echo 'lee ALL=(ALL) ALL' >> /etc/sudoers

USER lee

CMD ["/bin/bash"]

